add travis ci files

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,27 +1,50 @@
+
+
+# Copied from https://github.com/nim-lang/Nim/wiki/TravisCI
 language: c
+env:
+  # Build and test against the master and devel branches of Nim
+  - BRANCH=master
+  - BRANCH=devel
+compiler:
+  # Build and test using both gcc and clang
+  - gcc
+  - clang
+matrix:
+  allow_failures:
+    # Ignore failures when building against the devel Nim branch
+    - env: BRANCH=devel
+  fast_finish: true
 install:
   - |
-    # Download the latest release of Nim into the "nim-master" folder
-    git clone -b master --depth 1 git://github.com/nim-lang/nim nim-master/
-    cd nim-master
-    # Download the latest release of Nim's prepared C sources, for bootstrapping
-    git clone -b master --depth 1 git://github.com/nim-lang/csources csources/
-    cd csources
-    # Build C sources
-    sh build.sh
-    cd ..
-    # This concludes the first step of bootstrapping, don't need C sources anymore
-    rm -rf csources
-    # Use the executable built from C sources to compile the build tool
-    bin/nim c koch
-    # Compile Nim in release mode, using the Nim compiler we already have
-    ./koch boot -d:release
+    if [ ! -x nim-$BRANCH/bin/nim ]; then
+      git clone -b $BRANCH --depth 1 git://github.com/nim-lang/nim nim-$BRANCH/
+      cd nim-$BRANCH
+      git clone --depth 1 git://github.com/nim-lang/csources csources/
+      cd csources
+      sh build.sh
+      cd ..
+      rm -rf csources
+      bin/nim c koch
+      ./koch boot -d:release
+    else
+      cd nim-$BRANCH
+      git fetch origin
+      if ! git merge FETCH_HEAD | grep "Already up-to-date"; then
+        bin/nim c koch
+        ./koch boot -d:release
+      fi
+    fi
     cd ..
 before_script:
-  # Add the 'bin' folder to PATH
-  - export PATH="nim-master/bin:$PATH"
+    - export PATH="nim-$BRANCH/bin${PATH:+:$PATH}"
 script:
-  # Run 'tests/all.nim'. Feel free to change this, but it needs to be a program
-  # that returns a non-zero status code in case of failure. The testing facilities
-  # in Nim's standard library do this.
-  - nim compile --verbosity:0 --run tests/all
+    # Replace uppercase strings!
+    - nim c --cc:$CC --verbosity:0 -r SeriesManager/seriesManager.nim
+cache:
+  directories:
+    - nim-master
+    - nim-devel
+branches:
+  except:
+    - gh-pages
